apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm.fullname" . }}
    tier: gateway
