# Generated by Django 3.2.22 on 2024-03-05 22:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('categorie_id', models.IntegerField()),
                ('categorie_name', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=6, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comptes.categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrevisionRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Extrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=9)),
                ('label', models.CharField(max_length=200)),
                ('unicity_flag', models.IntegerField(default=0)),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('note', models.CharField(max_length=255)),
                ('categorie_month', models.DateField(null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.categorie')),
            ],
            options={
                'unique_together': {('date', 'montant', 'label', 'unicity_flag')},
            },
        ),
    ]
