# Generated by Django 3.2.22 on 2024-03-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_state_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('override', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptes.categorie')),
            ],
        ),
    ]
