# Generated by Django 3.2.22 on 2024-03-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_prevision_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevision',
            name='month',
        ),
        migrations.RemoveField(
            model_name='prevision',
            name='year',
        ),
    ]
