# Generated by Django 3.2.22 on 2024-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_encours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startSolde', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bilan', models.DecimalField(decimal_places=2, max_digits=9)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
