# Generated by Django 3.2.22 on 2024-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_monthsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
