# Generated by Django 3.2.22 on 2024-05-03 12:04

import datetime

from django.db import migrations


def fonction(apps, schema_editor):
    PrevisionRules = apps.get_model("comptes", "previsionrules")
    for rule in PrevisionRules.objects.all():
        rule.start = datetime.date(rule.start_year, rule.start_month, 1)
        if rule.end_year != None:
            rule.end = datetime.date(rule.end_year, rule.end_month, 1)
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0012_auto_20240503_1328"),
    ]

    operations = [
        migrations.RunPython(fonction),
    ]
