# Generated by Django 3.2.22 on 2024-05-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0016_encours_closed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prevision',
            new_name='Echeance',
        ),
    ]
