# Generated by Django 3.2.22 on 2024-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_prevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='collection',
            field=models.IntegerField(null=True),
        ),
    ]
