# Generated by Django 3.2.22 on 2024-03-13 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_prevision_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
