# Generated by Django 3.2.22 on 2024-05-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_auto_20240313_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('due_date', models.DateField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptes.categorie')),
            ],
        ),
    ]
