# Generated by Django 3.2.22 on 2024-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_alter_monthsummary_startsolde'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionrules',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='previsionrules',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
