# Generated by Django 3.2.22 on 2024-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0013_auto_20240503_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsionrules',
            name='start_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='previsionrules',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
