# Generated by Django 3.2.22 on 2024-05-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0014_auto_20240503_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsionrules',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='previsionrules',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='previsionrules',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='previsionrules',
            name='start_year',
        ),
    ]
