# Generated by Django 3.2.22 on 2024-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0015_auto_20240503_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='encours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
