# Generated by Django 3.2.22 on 2024-05-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0017_rename_prevision_echeance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.categorie')),
            ],
        ),
    ]
